clone:
  path: github.com/drone/drone

build:
  image: armhfbuild/drone-golang:1.5
  environment:
    - GO15VENDOREXPERIMENT=1
  commands:
    - make deps gen
    #- make test test_postgres test_mysql
    - make build build_static deb docs

#compose:
  #postgres:
    #image: postgres:9.4.5
    #environment:
      #- POSTGRES_USER=postgres
  #mysql:
    #image: mysql:5.6.27
    #environment:
      #- MYSQL_DATABASE=test
      #- MYSQL_ALLOW_EMPTY_PASSWORD=yes

publish:
  docker_master:
    image: armhfplugins/drone-docker:docker-caching
    username: $$DOCKER_USER
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: armhfbuild/drone
    tag:
      - "latest"
      - "0.4"
    when:
      repo: armhf-docker-library/drone
      branch: master

  docker_alpine:
    image: armhfplugins/drone-docker:docker-caching
    file: "Dockerfile-alpine"
    username: $$DOCKER_USER
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: armhfbuild/drone
    tag:
      - "0.4-alpine"
    when:
      repo: armhf-docker-library/drone
      branch: master

  docker_branch:
    image: armhfplugins/drone-docker:docker-caching
    username: $$DOCKER_USER
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: armhfbuild/drone
    tag: $$BRANCH
    when:
      repo: armhf-docker-library/drone

cache:
  mount:
    - /drone/docker

notify:
  slack:
    webhook_url: $$SLACK_WEBHOOK_URL
    channel: armhf
