FROM armhfbuild/alpine:3.3
RUN apk --update-cache add ca-certificates

EXPOSE 8000
COPY contrib/docker/etc/nsswitch.conf /etc/

ENV DATABASE_DRIVER=sqlite3
ENV DATABASE_CONFIG=/var/lib/drone/drone.sqlite

COPY drone_static /drone_static

ENTRYPOINT ["/drone_static"]
